// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAmqcwUF_EMW7Q6TY0KC6uKnghUOFpsm0',
    appId: '1:643162426084:android:9a9a4f8d98d3785d907af1',
    messagingSenderId: '643162426084',
    projectId: 'dealdock-custormer-app',
    storageBucket: 'dealdock-custormer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwPPcja5HfZV7wKH0blBO33XwvnsmccgA',
    appId: '1:643162426084:ios:b925324ec83bfa74907af1',
    messagingSenderId: '643162426084',
    projectId: 'dealdock-custormer-app',
    storageBucket: 'dealdock-custormer-app.firebasestorage.app',
    iosBundleId: 'com.dealdock.customer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsif3dsbpuKU8MU8792IWKuis5dcIyuYg',
    appId: '1:643162426084:web:fa07f2b820c4af16907af1',
    messagingSenderId: '643162426084',
    projectId: 'dealdock-custormer-app',
    authDomain: 'dealdock-custormer-app.firebaseapp.com',
    storageBucket: 'dealdock-custormer-app.firebasestorage.app',
    measurementId: 'G-0JKCZX3YKY',
  );

}
